### ISSUE TITLE
CoreHive

### ISSUE THREAD

**Issue by CoreHive** [xcat2/xcat2.github.io#103]
**Organization Name:** [ CoreHive] 

**Opt-in|Opt-out:** [ Opt-in]

**Provide a logo for us to use or a URL to an image:** [ http://corehive.com/wp-content/uploads/2018/05/Asset-12-e1526882625654.jpg] 

**Share your story (optional):**

*We would be thrilled to know how you are using xCAT.*

CoreHive use xCAT as our favorite tool to build, install, configure, secure, optimize and deliver valuable data insights and performance for your business-critical HPC application workloads on-premise and on the IBM Cloud or third-party clouds like Amazon AWS , Microsoft Azure.

**Comment by gurevichmark** [comment]
![image](https://user-images.githubusercontent.com/16106630/77695172-b5d01a00-6f81-11ea-91fb-d22487e3576f.png)
