### ISSUE TITLE
Remove the tabs in the download steps for go-xcat 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat2.github.io#15]
Minor issue, on the download page, the instructions have an extra tab into it... 

<img width="556" alt="image" src="https://user-images.githubusercontent.com/10049070/53749074-9a750700-3e74-11e9-9881-e051a6e83c93.png">

If I copy and paste that above into a term window: 

```
 wget https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT-server/share/xcat/tools/go-xcat -O - >/tmp/go-xcat
       chmod +x /tmp/go-xcat
       /tmp/go-xcat
```

I don't think the tabs are necessary, the code box is already highlighted in black.

**Comment by bybai** [comment]
fixed in http://xcat.org/download.html

**Comment by robin2008** [comment]
The tab is not there,  and just wondering  why not use `/tmp/go-xcat`, instead of `/tmp/go-xcat install -y`?

It is kinda of confusing when wen see 
`On the target xCAT Management Node, run the following commands to install the latest version of xCAT:`
