### ISSUE TITLE
Please avoid open new tab while click on hyperlink

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2.github.io#18]
**The problem recreation steps.**

1. Open `https://xcat.org/` in Chrome browser window.
1. Wait the web page finish load.
1. Click xCAT logo on top the web page.

**What was happening**

1. While a hyperlink was clicked, a new tab was opened. Now, there are two tabs for `http://xcat.org/`

**What is expected**

1. Avoid open new tab while click on hyperlink.

**Additional information**

1. Please notice the same thing happened on almost every hyperlink on this website. This behaviour is very annoy.

**Comment by gurevichmark** [comment]
Due to limited resources this issue will not be fixed.
