### ISSUE TITLE
The quick start link is missing after 2.14.6 release

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2.github.io#22]
Just go to the homepage. and surf to `Quick Start` section. Then click the url, and found it is missing.

The URL is `https://xcat-docs.readthedocs.io/en/latest/overview/quick_start.html`

**Comment by robin2008** [comment]
@bybai @hu-weihua  Do we missing some steps there?

**Comment by bybai** [comment]
let me quick fix it @robin2008

**Comment by bybai** [comment]
Fixed in https://github.com/xcat2/xcat2.github.io/pull/23
