### ISSUE TITLE
RedLine Performance Solutions, LLC

### ISSUE THREAD

**Issue by donavart** [xcat2/xcat2.github.io#34]
RedLine Performance Solutions, LLC

Opt-in

RedLine specializes in High Performance Computing (HPC) software and systems engineering, development, and support, from planning, designing, and implementation, to porting and performance tuning

We have been using xCat since early 2011.  We have deployed numerous clusters on many different hardware platforms. 

![RedLineHighRes](https://user-images.githubusercontent.com/3589632/57230769-17dd0500-6fe7-11e9-9bca-728fd5074aa2.png)

**Comment by bybai** [comment]
Hi @donavart,

We have added your organization logo and story in http://xcat.org//#who-is-using-xcat .
You can move mouse over your logo, and the story appears, if you have any problem, contact us freely.
