### ISSUE TITLE
[Logo] Versatus HPC

### ISSUE THREAD

**Issue by viniciusferrao** [xcat2/xcat2.github.io#35]
**Organization Name:** [Versatus HPC] 

URL: www.versatushpc.com.br

**Opt-in|Opt-out:** [Opt-in]

**Provide a logo for us to use or a URL to an image:** [http://www.versatushpc.com.br/logo2018.png] 

![www.versatushpc.com.br](http://www.versatushpc.com.br/logo2018.png)

**Share your story (optional):**
100% focused on High Performance Computing, Versatus HPC is a Brazilian company focused on delivering the best solutions for HPC scenarios in the academia, industries and businesses. With 10 years of experience we allow the researchers to focus exclusively on R&D pursuing its scientific objectives.

**We would be thrilled to know how you are using xCAT.**
We are supporting / installing xCAT in lot of Universities and Companies in Brazil. We always defaults to xCAT as the main provisioner and we try at best to convince our customers to move from whatever provisioning solution, including proprietary ones, to xCAT.

**Comment by bybai** [comment]
Hi @viniciusferrao, 
    We have added your organization logo and story in  http://xcat.org//#who-is-using-xcat .
    If you have any problem, contact us freely.
