### ISSUE TITLE
[Logo] Stanford Research Computing Center

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat2.github.io#36]
**Organization Name:** [Stanford Research Computing Center] 

**Opt-in|Opt-out:** [Opt-in]

**Provide a logo for us to use or a URL to an image:** ![](https://avatars3.githubusercontent.com/u/13439289?s=400&u=9ef618824655b9c2a3fea3af05c071ce36844241&v=4)

**Share your story (optional):**
The Stanford Research Computing Center (SRCC) is a joint effort of the Dean of Research and IT Services to build and support a comprehensive program to advance computational research at Stanford.  That includes offering and supporting traditional high-performance computing (HPC) systems, as well as systems for high throughput and data-intensive computing.  The SRCC also helps researchers transition their analyses and models from the desktop to more capable and plentiful resources, providing the opportunity to explore their data and answer research questions (on-premise or in the cloud) at a scale typically not possible on desktops or departmental servers.

*We would be thrilled to know how you are using xCAT.*
We use xCAT to deploy and maintain the [Sherlock cluster](www.sherlock.stanford.edu), Stanford's shared HPC cluster that features over 25,000 CPU cores and supports over 4,000 users.

**Comment by bybai** [comment]
Hi @kcgthb,

We have added your organization logo and story in http://xcat.org//#who-is-using-xcat .
You can move mouse over your logo, and the story appears, if you have any problem, contact us freely.

**Comment by kcgthb** [comment]
Thanks @bybai !

I forgot to add a link to our website: could you please modify the first line of the story to add the link, like this?
> The [Stanford Research Computing Center](https://srcc.stanford.edu) (SRCC) is a joint effort ...

Thanks!

**Comment by bybai** [comment]
@kcgthb, I updated it with above link. I will close this task. Thanks.
