### ISSUE TITLE
On the new webpage deployed, under News, change URLs referencing SourceForge to point to GitHub

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat2.github.io#51]
Under the News section, there's URLS that point to SourceForge. 

I'm actually wanting to slowly remove all references to source forge and I think we should decide  when to start deprecating.  When we moved to GitHub, I was met with a lot of resistance for not removing documentation on the Source Forge wiki.  

Now it's been 2 years, I think if the documentation section is already on RTD, we should deprecate it on SF so that it moves users towards the newer things that we want moving forward.  

However, this issue is just opened because 2 of the URLS under the "News" section point to SF, why is GitHub not used

**Comment by gurevichmark** [comment]
Added #63 to point to read the docs for building xCAT from source. 
The only remaining reference to sourceforge is the mailing list.
Due to lack of resources the mailing list will not be changed.
