### ISSUE TITLE
[Logo] OCF plc

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat2.github.io#59]
**Organization Name:** OCF plc

**Opt-in|Opt-out:** Opt-in

**Provide a logo for us to use or a URL to an image:**

![OCF-NoShadow-Large](https://user-images.githubusercontent.com/628790/59953749-66504100-9479-11e9-857f-557dcfdd1bf8.png)

https://www.ocf.co.uk

**Share your story (optional):**

Creating high performance computing, storage and data analytics that truly meet your needs

With over 15-years of experience in high performance computing and managing large-scale data challenges, our creative solutions could be just what your company is looking for.

From discovering the origins of the universe to statistical analysis of the genetics of the British population, we’re helping organisations like yours achieve amazing things.

**We would be thrilled to know how you are using xCAT.**

OCF supports and installs xCAT in over 95% of all our installations in the UK and Ireland. We have vast experience and have been developing and implementing xCAT since 2008. OCF deployed their first cluster in the UK using xCAT 2.0 soon after it was released. We pride ourselves in being one of the leading providers for xCAT solutions, and we would hope to tackle any problem that any individual faces.

**Comment by gurevichmark** [comment]
@arif-ali 
OCF logo and description have been added under #60, #61 abd #62
