### ISSUE TITLE
[Logo] BSC plc

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat2.github.io#68]
**Organization Name:** BSC

**Opt-in|Opt-out:** Opt-in

**Provide a logo for us to use or a URL to an image:** https://www.somma.es/sites/default/files/styles/large_without_crop/public/centers/logos/bsc%402x.jpg

**Share your story (optional):**

*We would be thrilled to know how you are using xCAT.*

Statelite cluster of 3,456 nodes (48 racks of 72 nodes). Since this is a statelite cluster we have a large amount of service nodes, which also serve as the NFS servers for the images (via GPFS cNFS) – one service node per 2 racks, i.e 24 service nodes in total.

**Comment by whowutwut** [comment]
Just FYI, We had gotten approval from the customer through email with Gliad on 6/26/19

> I am currently at BSC and you have the OK to use their logo on the site.
