### ISSUE TITLE
Vote for new xCAT logo

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2.github.io#7]
We are considering a refresh of the xCAT logo,  below you will find  some of the candidates. We would value your opinion  and feedback.

## Contending Logos 

See below for voting options and explanations about the logos.

![image](https://media.github.ibm.com/user/17872/files/09b5e1ec-1d9c-11e9-94a2-ac9198f22d65) ![image](https://media.github.ibm.com/user/17872/files/01ece2da-1d9c-11e9-8198-cd1aa953d32c) ![image](https://media.github.ibm.com/user/17872/files/f79b6932-1d9b-11e9-8779-bc853d438905)

**Comment by gurevichmark** [comment]
If someone knows how to do animation, we can even do some morphing from image 1 to image 2.

Start with 4 boxes and slowly move them together, then rotate, then move ears behind the face.
Finally lines connecting management node to computes become whiskers. Something like:

![image](https://user-images.githubusercontent.com/16106630/51495485-84aaf700-1d8a-11e9-98b3-2381ac1e3040.png)


![image](https://user-images.githubusercontent.com/16106630/51495743-5ed22200-1d8b-11e9-931e-d936db75d6c0.png)


![image](https://user-images.githubusercontent.com/16106630/51495874-d1db9880-1d8b-11e9-8b40-cb3240e4fe54.png)

**Comment by bybai** [comment]
## Logo 1

Cluster management meaning logo, the red box is xCAT management node, other 3 boxes represent different kinds of servers that can be provisioned in the cluster.  xCAT is a powerful tool to deploy  both bare metal and virtualized servers. 

![image](https://media.github.ibm.com/user/27933/files/f862dfda-1e31-11e9-8fe8-90b2d3cf37b0)

Please vote for this by 👍  on this comment

**Comment by bybai** [comment]
## Logo 2 

Here's logo 2, it looks like a CAT, the cluster looks like wiskers.

![image](https://media.github.ibm.com/user/27933/files/27e2ddc8-1e32-11e9-86ce-b6ae2ab6188b)

Please vote for this by 👍 on this comment

**Comment by bybai** [comment]
# Original Logo 

I don't like change, please keep this one!! 

<img width="208" alt="image" src="https://media.github.ibm.com/user/27933/files/c5c08c5a-1e34-11e9-9945-6afbfec7ea32">

**Comment by jjohnson42** [comment]
I put a vote for original logo just so visitors have an obvious thumb to click if they desire, I voted for all three to balance.

**Comment by NickyDaB** [comment]
I like number 2, but I would like to suggest some improvements. 

**Mock-up of improvements:** 
<img width="848" alt="image" src="https://user-images.githubusercontent.com/4662139/51632605-c0c29100-1f1d-11e9-996e-18777557f1c6.png">

**Suggestions Explained:** 
- Expand the upper and lower whiskers of the cluster to form the letter X. 
- Expand those outer whiskers to a "node" with a "container"  
- these changes combine our brand name of "xCAT" inside the logo, by both preserving the letter X and the image of the cat. while also showcasing what we do, via the cluster and node distribution hidden in the whiskers. 
- I would do a better mock up, but I don't have Photoshop on my work computer. 
- @whowutwut please sponsor me in requesting to get Jerry to approve me getting Photoshop installed on my work computer. 

I hope you consider my suggestions as reinforcing/combining the 3 components of a logo of "image", "name", and "purpose" is very powerful on how the human brain stores information, and will make for a much more powerful marketing potential.

**Comment by martinitime1975** [comment]
#2 would get my vote although its still a little busy for my taste, and it doesn't emphasize the X in xCAT.  I think the 'X' is ,more important than the 'cat'

**Comment by bybai** [comment]
Hi @jjohnson42, thanks your pointing out this, and voted for all three to balance.

**Comment by bybai** [comment]
Hi @NickyDaB and @martinitime1975 ,
Thanks for your precious suggestions and passion, especially your improvements. The first logo candidate is abstract and modern style logo representative.  The second logo candidate is cat visual and historic style logo representative. Currently, the first important thing is to decide to choose which style, let us vote for the style at first. After we decide logo style, we can pay little efforts to do small improvements to match the new home page, I think the following picture may be next to your suggestions, any way, I think let us vote style based on the above logo candidates first.
![image](https://user-images.githubusercontent.com/6743951/51666018-0d7a9a80-1ff8-11e9-8907-6531ebadc39b.png)

**Comment by NickyDaB** [comment]
ok. thank you for the clarification of voting for style. I have updated my vote.

**Comment by hellerda** [comment]
IMHO #2 is great as it is.  The connections as whiskers are perfect.  Leaving the space where the eyes would be, conveys the cat face nicely.

**Comment by bybai** [comment]
@Obihoernchen , thanks your comments.

**Comment by robin2008** [comment]
To close it as we choose one now, expect to create new ticket if you have better design.
