### ISSUE TITLE
Logos are breaking the website

### ISSUE THREAD

**Issue by viniciusferrao** [xcat2/xcat2.github.io#88]
**Issue description:**

The logos are breaking the interface, it happens with the BSC logo.

**Attach image (optional):**

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2031761/72462423-ce68ca80-37af-11ea-8739-80b2beaee1ea.png">

**Comment by gurevichmark** [comment]
Which browser it this with ?

**Comment by viniciusferrao** [comment]
Safari on macOS Catalina 10.15.2.

It breaks on Safari for iOS 13.3 too:

**Comment by gurevichmark** [comment]
Fixed by #89

**Comment by viniciusferrao** [comment]
@gurevichmark Fixed for Safari on macOS 10.15.2 but it generated another issue on Safari for iOS 13.3. The logos got through the division line and it's impossible to read the description.
![IMG_1898](https://user-images.githubusercontent.com/2031761/72479093-2adce180-37d2-11ea-8942-ff7abd7c5111.PNG)
