### ISSUE TITLE
Add logo for University of San Diego as xCAT user

### ISSUE THREAD

**Issue by kkeane** [xcat2/xcat2.github.io#92]
**Organization Name:** [ University of San Diego ] 

**Opt-in|Opt-out:** [ Opt In ]

**Provide a logo for us to use or a URL to an image:** [ https://www.sandiego.edu/brand/images/logos/master-primary/usd-logo-primary-2c.png ] 

**Share your story (optional):**

*We would be thrilled to know how you are using xCAT.*

**Comment by gurevichmark** [comment]
@kkeane Thanks for opening this issue to add U of San Diego to the xCAT web page.
Would you mind sharing how big of the cluster xCAT is managing and what architecture and OS is being used ?
