### ISSUE TITLE
Link to Cineca logo is broken on xcat.org

### ISSUE THREAD

**Issue by besawn** [xcat2/xcat2.github.io#93]
Using firefox 68.3.0esr (64-bit):
![image](https://user-images.githubusercontent.com/38794505/73190628-4316ff80-40f4-11ea-9af3-6330d3eaa1e5.png)

Let's discuss the best solution, but we should either update or remove the logo to fix the broken link.

**Comment by gurevichmark** [comment]
The logo image specified in `index.html` by https://www.cineca.it/sites/all/themes/cineca/logo.png is no longer there. Need to find the new location.

**Comment by gurevichmark** [comment]
Marco B, the contact for Cineca pointed to the official https://www.cineca.it/area-stampa/cartella-stampa which shows the new logo

**Comment by gurevichmark** [comment]
![image](https://user-images.githubusercontent.com/16106630/73305963-3aecbc00-41e9-11ea-99b9-d330295c973c.png)
